---

- name: "[dev/js] Install <nodejs@{{ macbook.development.js.node_version }}>"
  shell: |
    source {{ macbook.development.js.nvm_path }}/nvm.sh
    nvm install {{ macbook.development.js.node_version }}
