---

- name: "[dev/js] Remove old <nvm>"
  file:
    path: "{{ macbook.development.js.nvm_path }}"
    state: absent

- name: "[dev/js] Install <nvm@{{ macbook.development.js.nvm_version }}>"
  git:
    repo: https://github.com/nvm-sh/nvm
    dest: "{{ macbook.development.js.nvm_path }}"
    version: "{{ macbook.development.js.nvm_version }}"
