---

- name: '[dev/js] Remove old <nvm>'
  file:
    path: "{{ macos_js_env.nvm_path }}"
    state: absent

- name: "[dev/js] Install <nvm@{{ macos_js_env.nvm_version }}>"
  git:
    repo: "{{ macos_js_env.nvm_repo }}"
    dest: "{{ macos_js_env.nvm_path }}"
    version: "{{ macos_js_env.nvm_version }}"
