---

- name: '[dev/js] Remove old <nvm>'
  file:
    path: "{{ macoss_js_env.nvm_path }}"
    state: absent

- name: "[dev/js] Install <nvm@{{ macoss_js_env.nvm_version }}>"
  git:
    repo: https://github.com/nvm-sh/nvm
    dest: "{{ macoss_js_env.nvm_path }}"
    version: "{{ macoss_js_env.nvm_version }}"
