---

- name: '[macOS/DB] Install <clickhouse>'
  block:
    - name: '[clickhouse/brew/tap] Add clickhouse repository'
      homebrew_tap:
        name: clickhouse/clickhouse
        state: present
    - name: '[clickhouse/configs] Create homebrew-clickhouse Config directory'
      file:
        path: /opt/homebrew/etc/clickhouse-server
        state: directory
    - name: '[clickhouse/configs] Create homebrew-clickhouse Data directory'
      file:
        path: /opt/homebrew/var/lib/clickhouse/
        state: directory
    - name: '[clickhouse/configs] Seed default settings file'
      copy:
        dest: /opt/homebrew/etc/clickhouse-server/config.xml
        content: |
          <clickhouse>
              <logger>
                  <level>trace</level>
                  <console>true</console>
              </logger>
              <http_port>8123</http_port>
              <tcp_port>9000</tcp_port>
              <mysql_port>9004</mysql_port>
              <path>./</path>
              <mlock_executable>true</mlock_executable>
              <users>
                  <default>
                      <password/>
                      <networks>
                          <ip>::/0</ip>
                      </networks>
                      <profile>default</profile>
                      <quota>default</quota>
                      <access_management>1</access_management>
                  </default>
              </users>
              <profiles>
                  <default/>
              </profiles>
              <quotas>
                  <default/>
              </quotas>
          </clickhouse>
    - name: '[clickhouse/brew/install] Install <clickhouse>'
      homebrew:
        package: clickhouse/clickhouse/clickhouse@{{ macos_databases.clickhouse_version }}
        state: latest
      notify: brew_pkg_installed
