---

- name: "[macOS] Initial System Configuration"
  hosts: macbook
  gather_facts: yes
  tasks:
    - name: "[macOS] Update macOS"
      command: softwareupdate --install --all # analogue: -i -a

    # TODO: fix this task :\
    # - name: "[macOS] Set the soft file descriptor count to <unlimited>"
    #   command: launchctl limit maxfiles unlimited
    #   become: yes
    #   become_method: sudo

    - name: "[macOS/homebrew] prepare necessary directories for homebrew"
      # TODO: dunno why this fails
      # become: yes
      # become_method: sudo
      file:
        path: /usr/local/sbin # NOTE: can fail - run `sudo mkdir -p /usr/local/sbin` instead
        owner: "{{ my_macbook.home_user }}" # NOTE: chonw -R $(whoami) /usr/local/sbin
        state: directory
        recurse: yes

    - name: "[macOS/homebrew] check if homebrew is installed"
      stat:
        path: /usr/local/bin/brew
      register: macos_homebrew_status

    - name: "[macOS/homebrew] install homebrew"
      command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when: not macos_homebrew_status.stat.exists

    - name: "[macOS/homebrew] Update homebrew to the latest version"
      homebrew:
        update_homebrew: yes
