---

- name: "[macOS/dev/ruby] Prepare Ruby Environment"
  hosts: macbook
  gather_facts: yes

  tasks:
    - name: "[macOS/dev/ruby] Install <rbenv>"
      homebrew:
        package: rbenv
        state: latest
        update_homebrew: yes

    - name: "[macOS/dev/ruby] Install <ruby-build>"
      homebrew:
        package: ruby-build
        state: latest
        update_homebrew: yes

    - name: "[macOS/dev/ruby] Check installed ruby versions"
      shell: rbenv versions
      register: macbook_rbenv_ruby_versions

    - name: "[macOS/dev/ruby] Install <ruby@{{ macbook.development.ruby.ruby_version }}>"
      shell: rbenv install {{ macbook.development.ruby.ruby_version }}
      when: macbook.development.ruby.ruby_version not in macbook_rbenv_ruby_versions.stdout

    - name: "[macOS/dev/ruby] Install <bundler@{{ macbook.development.ruby.bundler_version }}>"
      become: yes
      become_user: "{{ macbook.home_user }}"
      shell: |
        rbenv local {{ macbook.development.ruby.ruby_version }}
        gem install bundler --version={{ macbook.development.ruby.bundler_version }}
