---

- name: '[dev/elixir] Remove old <asdf>'
  file:
    path: "{{ macos_elixir_env.asdf_path }}"
    state: absent

- name: "[dev/elixir] Copy repository <asdf@{{ macos_elixir_env.asdf_version }}"
  git:
    repo: "{{ macos_elixir_env.asdf_repo }}"
    dest: "{{ macos_elixir_env.asdf_path }}"
    version: "{{ macos_elixir_env.asdf_version }}"
