---

- name: '[dev/elixir-deps/erlang] Install erlang plugin'
  shell: |
    set -o pipefail
    . {{ macos_elixir_env.asdf_path }}/asdf.sh
    asdf plugin-add erlang
  ignore_errors: true # it happens only when the erlang plugin is already installed

- name: '[dev/elixir-deps/erlang] Check installed erlang versions'
  shell: |
    set -o pipefail
    . {{ macos_elixir_env.asdf_path }}/asdf.sh
    asdf list erlang
  register: installed_erlang_versions
  ignore_errors: true

- name: "[dev/elixir-deps/erlang] Install <erlang@{{ macos_elixir_env.erlang_version }}>"
  shell: |
    set -o pipefail
    . {{ macos_elixir_env.asdf_path }}/asdf.sh
    asdf install erlang {{ macos_elixir_env.erlang_version }}
  when: macos_elixir_env.erlang_version not in installed_erlang_versions
