---

- name: '[macOS/monitoring] Install <influxdb>'
  block:
    - name: '[macos/monitoring/influxdb] Install <influxdb>'
      homebrew:
        package: influxdb
        state: latest
      notify: brew_pkg_installed

    - name: '[macos/monitoring/influxdb] Install <influxdb-cli>'
      homebrew:
        package: influxdb-cli
        state: latest
      notify: brew_pkg_installed
