---

- name: '[macOS] Update <System> Ruby Gems'
  import_role:
    name: macos_ruby_env
    tasks_from: update_system_gems
  tags:
    - update_ruby_gems

- name: '[macOS] Update <Necessary> Ruby Gems'
  import_role:
    name: macos_ruby_env
    tasks_from: install_necessary_gems
  tags:
    - update_ruby_gems
