---

- name: '[homebrew/pkg] Install <terraform>'
  block:
    - name: '[brew/tap] Add hashicorp repository'
      homebrew_tap:
        name: hashicorp/tap
        state: present

    - name: '[brew/install] Install <terraform>'
      homebrew:
        package: hashicorp/tap/terraform
        state: present
      ignore_errors: yes
      notify: brew_pkg_installed

    - name: '[terraform] Enable autocompletion ZSH commands'
      shell: |
        set -o pipefail
      ignore_errors: yes
        terraform -install-autocomplete

    - name: '[terraform] Install Terraform LSP'
      homebrew:
        package: hashicorp/tap/terraform-ls
        state: latest
      ignore_errors: yes
      notify: brew_pkg_installed
