---

- name: "[dev/ruby] Install required gems" # NOTE: if fails use: eval "$(rbenv init -)";
  shell: |
    eval "$(rbenv init -)"
    rbenv global {{ macos_ruby_env.ruby_version }}
    gem install {{ required_gem }}
  loop:
    - "bundler --version={{ macos_ruby_env.bundler_version }}"
    - "steep"
    - "typeprof"
    - "rbs"
    - "pry"
    - "pry-doc"
  loop_control:
    loop_var: required_gem
