---

- name: "[dev/ruby] Install <bundler@{{ macos_ruby_env.bundler_version }}>"
  shell: | # NOTE: if fails use: eval "$(rbenv init -)";
    rbenv init
    rbenv shell {{ macos_ruby_env.ruby_version }}
    gem install bundler --version={{ macos_ruby_env.bundler_version }}
