---

- name: '[dev/ruby] Install <solargraph>'
  block:
    - name: '[dev/ruby] solargraph: install gem'
      shell: |
        set -o pipefail
        eval "$(rbenv init -)"
        rbenv global {{ macos_ruby_env.ruby_version }}
        gem install solargraph -v {{ macos_ruby_env.solargraph_version }}
    - name: '[dev/ruby] solargraph: configure'
      shell: solargraph download-core {{ macos_ruby_env.solargraph_core }}
