---

- name: 'Setup Ruby environment'
  include_tasks: "{{ item }}.yml"
  with_items:
    - install_rbenv
    - install_ruby
    - configure_ruby
    - setup_rubygems
    - install_necessary_gems
    - install_solargraph
    - install_seeing_is_believing_version
    - install_ruby_type_checkers
