---

- name: 'Setup Ruby environment'
  include_tasks: "{{ item }}.yml"
  with_items:
    - install_rbenv
    - install_ruby
    - isntall_truffleruby
    - configure_ruby
    - setup_rubygems
    - install_necessary_gems
    - install_solargraph
    - install_type_checkers
