---

- name: '[macos/dots] Copy dotfiles'
  block:
    - name: '[macos/dots] drop old .zsh/ directory'
      file:
        path: "{{ macbook.home_path }}/.zsh/"
        state: absent
    - name: '[macos/dots] drop old Midnight Commander settings'
      file:
        path: "{{ macos_post_config.midnight_commander_path }}/ini"
        state: absent
    - name: '[macos/dots] copy dot-files and .zsh/-directory'
      copy:
        src: "dotfiles/{{ dotfile }}"
        dest: "{{ macbook.home_path }}/{{ dotfile }}"
        owner: "{{ macbook.home_user }}"
      loop:
        - .bash_profile
        - .gitconfig
        - .gitignore
        - .nvmrc
        - .pryrc
        - .psqlrc
        - .python-version
        - .ruby-version
        - .tmux.conf
        - .vimrc
        - .zsh/
        - .zshrc
        - .ansible.cfg
        - .asdfrc
        - .tool-versions
        - .railsrc
      loop_control:
        loop_var: dotfile
    - name: '[macos/dots] Copy Midnight Commander Configs'
      copy:
        src: "dotfiles/midnight_commander/ini"
        dest: "{{ macos_post_config.midnight_commander_path }}/ini"
        owner: "{{ macbook.home_user }}"
