---

- name: '[dev/all] Prepare ~/Projects directory'
  file:
    path: "{{ macbook.home_path }}/Projects"
    state: directory

- name: '[dev/all] Clone projects'
  vars:
    github_url: "https://github.com/0exp"
    clone_path: "{{ macbook.home_path }}/Projects"
  git:
    repo: "{{ github_url }}/{{ repo_name }}"
    dest: "{{ clone_path }}/{{ repo_name }}"
    version: 'HEAD'
  loop:
    - cybercore
    - armonica
    - diablo-ruby
    - qonfig
    - any_cache
    - armitage
    - jaina
    - smart_core
    - symbiont-ruby
    - rabbit_matcher
    - sidekiq-portal
    - recipes
    - evil_events
    - 0exp.github.io
    - blast_wave
  loop_control:
    loop_var: repo_name
