---

- name: '[macos/dots] Copy dotfiles'
  block:
    - file:
        src: "{{ macbook.home_path }}/.zsh/"
        state: absent
    - copy:
        src: "dotfiles/{{ dotfile }}"
        dest: "{{ macbook.home_path }}/{{ dotfile }}"
        owner: "{{ macbook.home_user }}"
      loop:
        - .gitconfig
        - .gitignore
        - .nvmrc
        - .pryrc
        - .psqlrc
        - .tmux.conf
        - .vimrc
        - .zsh/
        - .zshrc
        - .ruby-version
      loop_control:
        loop_var: dotfile
