---

- name: '[macOS] Install shell prompt <spaceship-prompt>'
  vars:
    repo_url: https://github.com/denysdovhan/spaceship-prompt.git
    clone_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt"
    cloned_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt/spaceship.zsh-theme"
    final_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship.zsh-theme"
  block:
    - name: '[spaceship-prompt] remove already installed version'
      npm:
        name: spaceship-prompt
        global: yes
        state: absent
    - name: '[spaceship-prompt] install new version'
      npm:
        name: spaceship-prompt
        global: yes
    - name: '[spaceship-prompt] clone originals'
      git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_path }}"
        version: 'HEAD'
    - name: '[spaceship-prompt] link zsh theme'
      file:
        src: "{{ cloned_theme_path }}"
        dest: "{{ final_theme_path }}"
        state: link
