---

- name: '[macOS] Install zsh prompt <space-ship-prompt>'
  vars:
    prompt_repo_url: https://github.com/denysdovhan/spaceship-prompt.git
    prompt_themes_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt"
    prompt_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt/spaceship.zsh-theme"
    final_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship.zsh-theme"
  shell: |
    yarn global add spaceship-prompt
    git clone {{ prompt_repo_url }} "{{ prompt_themes_path }}"
    ln -s "{{ prompt_theme_path }}" "{{ final_theme_path }}"
