---

- name: '[macOS] Install zsh prompt <space-ship-prompt>'
  vars:
    repo_url: https://github.com/denysdovhan/spaceship-prompt.git
    clone_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt"
    cloned_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship-prompt/spaceship.zsh-theme"
    final_theme_path: "{{ macos_post_config.oh_my_zsh_path }}/themes/spaceship.zsh-theme"
  block:
    - npm: # NOTE: remove already installed version
        name: spaceship-prompt
        global: yes
        state: absent
    - npm: # NOTE: install new version
        name: spaceship-prompt
        global: yes
    - git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_path }}"
    - file:
        src: "{{ cloned_theme_path }}"
        dest: "{{ final_theme_path }}"
        state: link
