---

- name: 'Post-configurations for macOS environment'
  include_tasks: "{{ item }}.yml"
  with_items:
    - setup_favorite_fonts
    - install_spaceship_prompt
    - configure_vim
    - copy_dotfiles
    - copy_all_my_projects