---

- name: '[macOS] Setup faworite fonts'
  vars: { fonts_path: "{{ macbook.home_path }}/Library/Fonts" }
  copy:
    src: "dotfiles/fonts/{{ font_file }}"
    dest: "{{ fonts_path }}/{{ font_file }}"
    owner: "{{ macbook.home_user }}"
  loop:
    - FiraCode-Bold.ttf
    - FiraCode-Light.ttf
    - FiraCode-Medium.ttf
    - FiraCode-Regular.ttf
    - FiraCode-Retina.ttf
    - FiraCode-SemiBold.ttf
    - FiraCode-VF.ttf
    - JetBrainsMono-Bold.ttf
    - JetBrainsMono-BoldItalic.ttf
    - JetBrainsMono-ExtraBold.ttf
    - JetBrainsMono-ExtraBoldItalic.ttf
    - JetBrainsMono-ExtraLight.ttf
    - JetBrainsMono-ExtraLightItalic.ttf
    - JetBrainsMono-Italic.ttf
    - JetBrainsMono-Light.ttf
    - JetBrainsMono-LightItalic.ttf
    - JetBrainsMono-Medium.ttf
    - JetBrainsMono-MediumItalic.ttf
    - JetBrainsMono-Regular.ttf
    - JetBrainsMono-SemiBold.ttf
    - JetBrainsMono-SemiBoldItalic.ttf
    - JetBrainsMono-Thin.ttf
    - JetBrainsMono-ThinItalic.ttf
    - JetBrainsMonoNL-Bold.ttf
    - JetBrainsMonoNL-BoldItalic.ttf
    - JetBrainsMonoNL-ExtraBold.ttf
    - JetBrainsMonoNL-ExtraBoldItalic.ttf
    - JetBrainsMonoNL-ExtraLight.ttf
    - JetBrainsMonoNL-ExtraLightItalic.ttf
    - JetBrainsMonoNL-Italic.ttf
    - JetBrainsMonoNL-Light.ttf
    - JetBrainsMonoNL-LightItalic.ttf
    - JetBrainsMonoNL-Medium.ttf
    - JetBrainsMonoNL-MediumItalic.ttf
    - JetBrainsMonoNL-Regular.ttf
    - JetBrainsMonoNL-SemiBold.ttf
    - JetBrainsMonoNL-SemiBoldItalic.ttf
    - JetBrainsMonoNL-Thin.ttf
    - JetBrainsMonoNL-ThinItalic.ttf
    - MartianMono-CnBd.ttf
    - MartianMono-CnLt.ttf
    - MartianMono-CnMd.ttf
    - MartianMono-CnRg.ttf
    - MartianMono-CnTh.ttf
    - MartianMono-CnxBd.ttf
    - MartianMono-CnxLt.ttf
    - MartianMono-NrBd.ttf
    - MartianMono-NrLt.ttf
    - MartianMono-NrMd.ttf
    - MartianMono-NrRg.ttf
    - MartianMono-NrTh.ttf
    - MartianMono-NrxBd.ttf
    - MartianMono-NrxLt.ttf
    - MartianMono-StdBd.ttf
    - MartianMono-StdLt.ttf
    - MartianMono-StdMd.ttf
    - MartianMono-StdRg.ttf
    - MartianMono-StdTh.ttf
    - MartianMono-StdxBd.ttf
    - MartianMono-StdxLt.ttf
    - MartianMono-sWdBd.ttf
    - MartianMono-sWdLt.ttf
    - MartianMono-sWdMd.ttf
    - MartianMono-sWdRg.ttf
    - MartianMono-sWdTh.ttf
    - MartianMono-sWdxBd.ttf
    - MartianMono-sWdxLt.ttf
  loop_control:
    loop_var: font_file
