---

- name: '[homebrew] Prepare necessary directories for Homebrew'
  file:
    path: /usr/local/sbin # NOTE: can fail - run `sudo mkdir -p /usr/local/sbin` instead
    owner: "{{ macbook.home_user }}" # NOTE: chown -R $(whoami) /usr/local/sbin
    state: directory
    recurse: yes

- name: '[homebrew] Check Homebrew installation status'
  stat:
    path: /opt/homebrew/bin/brew
  register: macos_homebrew_status

- name: '[homebrew] Check and Install homebrew'
  vars: { macos_homebrew_url: 'https://raw.githubusercontent.com/Homebrew/install/master/install' }
  block:
    - name: '[gather-homebrew-existence]'
      stat:
        path: /opt/homebrew/bin/brew
      register: macos_homebrew_status
    - name: '[install-homebrew-if-it-does-not-exist]'
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not macos_homebrew_status.stat.exists

- name: '[homebrew] Update homebrew to the latest version'
  homebrew:
    update_homebrew: yes
