---

- name: '[macOS] Install general system-wide dependencies'
  homebrew:
    package: "{{ dependency }}"
    state: present
    update_homebrew: yes
  loop:
    - automake
    - autoconf
    - openssl
    - readline
    - sqlite3
    - xz
    - zlib
    - libxslt
    - libtool
    - libyaml
    - unixodbc
    - unzip
    - curl
    - fop
    - git
    - coreutils
  loop_control:
    loop_var: dependency
