---

- name: '[macOS] Remove old <oh-my-zsh>'
  file:
    path: "{{ macbook.home_path }}/{{ oh_my_zsh_file }}"
    state: absent
  loop:
    - .oh-my-zsh
    - .zshrc
  loop_control:
    loop_var: oh_my_zsh_file

- name: '[macOS] Install <oh-my-zsh>'
  vars: { macos_oh_my_zsh_url: 'https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh' }
  shell: sh -c "$(curl -fsSL {{ macos_oh_my_zsh_url }})"

- name: '[macOS] Instlal <zsh-autosuggestions>'
  vars:
    repo_url: https://github.com/zsh-users/zsh-autosuggestions
    clone_path: "{{ macbook.home_path }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ clone_path }}"
    version: HEAD

- name: '[macOS] Set oh-my-zsh as default shell'
  shell: chsh -s $(which zsh)
